version: '3.8'

services:
  web:
    build: ./web_backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web_backend/:/usr/src/web_backend/
    ports:
      - 8000:8000
    env_file:
      - ./web_backend/.env.dev

    depends_on:
      - db
    restart: always


  db:
    image: postgres:16
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=shalchian
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=web_backend

volumes:
  postgres_data: